//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_de_contabilidad_Open_Source.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asientoContable
    {
        public int asientoContableID { get; set; }
        public string descripcion { get; set; }
        public int identificadorAuxiliar { get; set; }
        public int cuenta { get; set; }
        public string tipoMovimiento { get; set; }
        public System.DateTime fecha { get; set; }
        public double monto { get; set; }
        public bool estado { get; set; }
        public int tipoMoneda { get; set; }
    
        public virtual cuentasAuxiliares cuentasAuxiliares { get; set; }
        public virtual cuentasContables cuentasContables { get; set; }
        public virtual tipoMonedas tipoMonedas { get; set; }
    }
}
