//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_de_contabilidad_Open_Source.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuentasContables
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cuentasContables()
        {
            this.asientoContable = new HashSet<asientoContable>();
        }
    
        public int cuentasContablesID { get; set; }
        public string Descripcion { get; set; }
        public int tipoCuenta { get; set; }
        public bool permiteTrans { get; set; }
        public string nivel { get; set; }
        public int cuentaMayor { get; set; }
        public double balance { get; set; }
        public bool estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asientoContable> asientoContable { get; set; }
        public virtual tipoCuentas tipoCuentas { get; set; }
    }
}
