//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_de_contabilidad_Open_Source.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Segundo_Parcial_Integracion_con_Open_SourceEntities : DbContext
    {
        public Segundo_Parcial_Integracion_con_Open_SourceEntities()
            : base("name=Segundo_Parcial_Integracion_con_Open_SourceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<asientoContable> asientoContable { get; set; }
        public virtual DbSet<cuentasAuxiliares> cuentasAuxiliares { get; set; }
        public virtual DbSet<cuentasContables> cuentasContables { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tipoCuentas> tipoCuentas { get; set; }
        public virtual DbSet<tipoMonedas> tipoMonedas { get; set; }
    }
}
