'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class asientoContable
    Public Property asientoContableID As Integer
    Public Property descripcion As String
    Public Property identificadorAuxiliar As Integer
    Public Property cuenta As Integer
    Public Property tipoMovimiento As String
    Public Property fecha As Date
    Public Property monto As Double
    Public Property estado As Boolean
    Public Property tipoMoneda As Integer

    Public Overridable Property cuentasAuxiliares As cuentasAuxiliares
    Public Overridable Property cuentasContables As cuentasContables
    Public Overridable Property tipoMonedas As tipoMonedas

End Class
