'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class Segundo_Parcial_Integracion_con_Open_SourceEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=Segundo_Parcial_Integracion_con_Open_SourceEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property asientoContable() As DbSet(Of asientoContable)
    Public Overridable Property cuentasAuxiliares() As DbSet(Of cuentasAuxiliares)
    Public Overridable Property cuentasContables() As DbSet(Of cuentasContables)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagrams)
    Public Overridable Property tipoCuentas() As DbSet(Of tipoCuentas)
    Public Overridable Property tipoMonedas() As DbSet(Of tipoMonedas)

End Class
