'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tipoCuentas
    Public Property tipoCuentasID As Integer
    Public Property Descripcion As String
    Public Property origen As String
    Public Property estado As Boolean

    Public Overridable Property cuentasContables As ICollection(Of cuentasContables) = New HashSet(Of cuentasContables)

End Class
