'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tipoMonedas
    Public Property tipoMonedasID As Integer
    Public Property Descripcion As String
    Public Property tasaCambiaria As Double
    Public Property estado As Boolean

    Public Overridable Property asientoContable As ICollection(Of asientoContable) = New HashSet(Of asientoContable)

End Class
